steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--path=.'
images:
  - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME'
